routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\FrontEndController;
use App\Http\Controllers\PostsController;
use App\Http\Controllers\TagsController;

Route::get('/', [FrontEndController::class, 'index'])->name('blogs.index');
Route::get('/categories/{category}', [FrontEndController::class, 'category'])->name('blogs.category');
Route::get('/tags/{tag}', [FrontEndController::class, 'tag'])->name('blogs.tag');

Route::get('/blogs/{post}', [FrontEndController::class, 'show'])->name('blogs.show');

Route::prefix('admin')->middleware('auth')->group(function () {
    Route::get('/dashboard', function () {
        return view('admin-panel.dashboard');
    })->name('dashboard');
    Route::resource('tags', TagsController::class)->except('show');
    Route::resource('categories', CategoriesController::class)->except('show');
    Route::resource('posts', PostsController::class);
    Route::put('posts/{post}/publish-now', [PostsController::class, 'publish'])->name('posts.publish');

    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Post extends Model
{
    use HasFactory;
    protected $guarded = [];

    protected function casts(): array
    {
        return[
            'published_at' => 'datetime'
        ];
    }

    public function tags(){
        return $this->belongsToMany(Tag::class);
    }
    public function category(){
        return $this->belongsTo(Category::class);
    }
    public function author(){
        return $this->belongsTo(User::class, 'user_id');
    }

    public function scopePublished($query) {
        return $query->whereNotNull('published_at');
    }
    public function scopeSearch($query) {
        $searchKey = request('search');

        if($searchKey) {
            $query = $query->where('title', 'like', "%${searchKey}%");
        }

        return $query;
    }

    public function getStatusAttribute(){
        return $this->published_at === null ? "<span class='badge bg-warning'>Draft</span>" : "<span class='badge bg-success'>Published</span>";
    }

    public function getIsPublishedAttribute() {
        return $this->published_at !== null;
    }
    public function getImageAttribute() {
        return 'storage/'. $this->image_path;
    }

    public function deleteImage(): bool {
        return Storage::delete($this->image_path);
    }
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreatePostRequest;
use App\Http\Requests\UpdatePostRequest;
use App\Models\Category;
use App\Models\Post;
use App\Models\Tag;
use Illuminate\Http\Request;
use Illuminate\Routing\Controllers\HasMiddleware;
use Illuminate\Routing\Controllers\Middleware;

class PostsController extends Controller implements HasMiddleware
{
    /**
     * Display a listing of the resource.
     */
    public static function middleware(){
        return [
            new Middleware('verifyUserForEditAndDelete', only: ['edit', 'update', 'delete', 'publish']),
        ];
    }

    public function index()
    {

        if(auth()->user()->isAdmin()) {
            $posts = Post::latest('updated_at')->paginate(10);
        } else {
            $posts = Post::where('user_id', auth()->id())->latest('updated_at')->paginate(10);
        }
        return view('admin-panel.posts.index', compact('posts'));
    }

    public function create()
    {
        $categories = Category::all();
        $tags = Tag::all();
        return view('admin-panel.posts.create', compact(['categories', 'tags']));
    }

    public function store(CreatePostRequest $request)
    {
        $image = $request->file('image')->store('images/posts');
        $post = Post::create([
            'title' => $request->title,
            'excerpt' => $request->excerpt,
            'body' => $request->body,
            'published_at' => $request->published_at,
            'category_id' => $request->category_id,
            'image_path' => $image,
            'user_id' => 1
        ]);

        $post->tags()->attach($request->tags);

        return redirect(route('posts.index'))->with('success', 'Post created successfully');
    }

    /**
     * Display the specified resource.
     */
    public function show(Post $post)
    {
        //
    }

    public function edit(Post $post)
    {
        $categories = Category::all();
        $tags = Tag::all();
        return view('admin-panel.posts.edit', compact(['categories', 'tags', 'post']));
    }

    public function update(UpdatePostRequest $request, Post $post)
    {
        $data = $request->only(['title', 'excerpt', 'body', 'published_at', 'category_id']);

        if($request->hasFile('image')) {
            $data['image_path'] = $request->file('image')->store('images/posts');
            $post->deleteImage();
        }
        $post->update($data);
        $post->tags()->sync($request->tags);

        session()->flash('success', 'Post updated successfully');
        return(redirect(route('posts.index')));
    }

    public function publish(Request $request, Post $post) {
        $post->published_at = now();
        $post->save();
        session()->flash('success', 'Post updated successfully');
        return(redirect(route('posts.index')));
    }

    public function destroy(Post $post)
    {
        $post->deleteImage();
        $post->delete();
        session()->flash('success', 'Post deleted successfully');
        return(redirect(route('posts.index')));
    }
}

resources/views/admin-panel/posts/create.blade.php
@extends('admin-panel.layouts.admin')

@section('page-level-styles')
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/trix@2.0.8/dist/trix.css">
@endsection

@section('admin-panel-content')
    <div class="container-fluid my-4 px-4">
        <div class="card mb-4">
            <div class="card-header d-flex justify-content-between">
                <h2 class="mt-4 d-inline-block">Add Post</h2>
            </div>

            <div class="card-body">
                <div class="datatable-wrapper datatable-loading no-footer sortable searchable fixed-columns">
                    <form action={{ route('posts.store')}} method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="mb-3">
                            <label for="name" class="form-label">Title</label>
                            <input type="text" name="title"  class="form-control @error('title') is-invalid @enderror" id="title" placeholder="Post's title" value="{{old('title')}}">
                            <div id="nameHelp" class="form-text text-danger">
                                @error('title')
                                    <div class="invalid-feedback">
                                        {{$message}}
                                    </div>
                                @enderror
                            </div>
                        </div>

                        <div class="mb-3">
                            <label for="excerpt" class="form-label">Excerpt</label>
                            <textarea type="text" name="excerpt"  class="form-control @error('excerpt') is-invalid @enderror" id="excerpt">{{old('excerpt')}}</textarea>
                            <div id="nameHelp" class="form-text text-danger">
                                @error('excerpt')
                                    <div class="invalid-feedback">
                                        {{$message}}
                                    </div>
                                @enderror
                            </div>
                        </div>

                        <div class="mb-3">
                            <label for="category_id" class="form-label">Category</label>
                            <select name="category_id"  class="select2 form-control" id="category_id" value="{{old('category')}}">
                                <option value="select..." selected disabled>Select...</option>
                                @foreach ($categories as $category)
                                    <option value="{{ $category->id }}" {{ $category->id === old('category_id') ? 'selected' : ''}}>{{ $category->name }}</option>
                                @endforeach
                            </select>
                            <div id="nameHelp" class="form-text text-danger">
                                @error('category_id')
                                    <div class="invalid-feedback">
                                        {{$message}}
                                    </div>
                                @enderror
                            </div>
                        </div>

                        <div class="mb-3">
                            <label for="body" class="form-label">Body</label>
                            <input type="hidden" name="body"  class="form-control @error('body') is-invalid @enderror" id="body" value="{{old('body')}}">
                            <trix-editor input="body"></trix-editor>
                            <div id="nameHelp" class="form-text text-danger">
                                @error('body')
                                    <div class="invalid-feedback">
                                        {{$message}}
                                    </div>
                                @enderror
                            </div>
                        </div>

                        <div class="mb-3">
                            <label for="image" class="form-label">Image</label>
                            <input type="file" name="image"  class="form-control" id="image" accept=".jpg,.gif,.png">
                            <div id="nameHelp" class="form-text text-danger">
                                @error('image')
                                    <div class="invalid-feedback">
                                        {{$message}}
                                    </div>
                                @enderror
                            </div>
                        </div>

                        <div class="mb-3">
                            <label for="published_at" class="form-label">Published At</label>
                            <input type="datetime-local" name="published_at"  class="form-control" id="published_at">
                            <div id="nameHelp" class="form-text text-danger">
                                Keep it blank to save it as draft
                            </div>
                        </div>

                        <div class="mb-3">
                            <label for="tags" class="form-label">Tags</label>
                            <select name="tags[]" class="form-control select2" id="tags" multiple="multiple">
                                @foreach ($tags as $tag)
                                    <option value="{{ $tag->id }}">{{ $tag->name }}</option>
                                @endforeach
                            </select>
                            <div id="nameHelp" class="form-text text-danger">
                                @error('tags')
                                    <div class="invalid-feedback">
                                        {{$message}}
                                    </div>
                                @enderror
                            </div>
                        </div>

                        <button type="submit" class="btn btn-primary mt-3">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('page-level-scripts')
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script type="text/javascript" src="https://unpkg.com/trix@2.0.8/dist/trix.umd.min.js"></script>
@endsection

resources/views/admin-panel/posts/edit.blade.php
@extends('admin-panel.layouts.admin')

@section('page-level-styles')
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/trix@2.0.8/dist/trix.css">
@endsection

@section('admin-panel-content')
    <div class="container-fluid my-4 px-4">
        <div class="card mb-4">
            <div class="card-header d-flex justify-content-between">
                <h2 class="mt-4 d-inline-block">Edit Post</h2>
            </div>

            <div class="card-body">
                <div class="datatable-wrapper datatable-loading no-footer sortable searchable fixed-columns">
                    <form action={{ route('posts.update', $post)}} method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="mb-3">
                            <label for="name" class="form-label">Title</label>
                            <input type="text" name="title"  class="form-control @error('title') is-invalid @enderror" id="title" placeholder="Post's title" value="{{old('title', $post->title)}}">
                            <div id="nameHelp" class="form-text text-danger">
                                @error('title')
                                    <div class="invalid-feedback">
                                        {{$message}}
                                    </div>
                                @enderror
                            </div>
                        </div>

                        <div class="mb-3">
                            <label for="excerpt" class="form-label">Excerpt</label>
                            <textarea type="text" name="excerpt"  class="form-control @error('excerpt') is-invalid @enderror" id="excerpt">{{old('excerpt', $post->excerpt)}}</textarea>
                            <div id="nameHelp" class="form-text text-danger">
                                @error('excerpt')
                                    <div class="invalid-feedback">
                                        {{$message}}
                                    </div>
                                @enderror
                            </div>
                        </div>

                        <div class="mb-3">
                            <label for="category_id" class="form-label">Category</label>
                            <select name="category_id"  class="select2 form-control" id="category_id" value="{{old('category')}}">
                                <option value="select..." selected disabled>Select...</option>
                                @foreach ($categories as $category)
                                    <option value="{{ $category->id }}" {{ $category->id === old('category_id', $post->category_id) ? 'selected' : ''}}>{{ $category->name }}</option>
                                @endforeach
                            </select>
                            <div id="nameHelp" class="form-text text-danger">
                                @error('category_id')
                                    <div class="invalid-feedback">
                                        {{$message}}
                                    </div>
                                @enderror
                            </div>
                        </div>

                        <div class="mb-3">
                            <label for="body" class="form-label">Body</label>
                            <input type="hidden" name="body"  class="form-control @error('body') is-invalid @enderror" id="body" value="{{old('body', $post->body)}}">
                            <trix-editor input="body"></trix-editor>
                            <div id="nameHelp" class="form-text text-danger">
                                @error('body')
                                    <div class="invalid-feedback">
                                        {{$message}}
                                    </div>
                                @enderror
                            </div>
                        </div>

                        <div class="mb-3">
                            <label for="image" class="form-label">Image</label>
                            <input type="file" name="image"  class="form-control" id="image" accept=".jpg,.gif,.png">
                            <div id="nameHelp" class="form-text text-danger">
                                @error('image')
                                    <div class="invalid-feedback">
                                        {{$message}}
                                    </div>
                                @enderror
                            </div>
                        </div>

                        <div class="mb-3">
                            <label for="published_at" class="form-label">Published At</label>
                            <input type="datetime-local" name="published_at"  class="form-control" id="published_at">
                            <div id="nameHelp" class="form-text text-danger">
                                Keep it blank to save it as draft
                            </div>
                        </div>

                        <div class="mb-3">
                            <label for="tags" class="form-label">Tags</label>
                            <select name="tags[]" class="form-control select2" id="tags" multiple="multiple">
                                @foreach ($tags as $tag)
                                    <option value="{{ $tag->id }}" {{ in_array($tag->id, $post->tags->pluck('id')->toArray()) ? 'selected' : '' }}>{{ $tag->name }}</option>
                                @endforeach
                            </select>
                            <div id="nameHelp" class="form-text text-danger">
                                @error('tags')
                                    <div class="invalid-feedback">
                                        {{$message}}
                                    </div>
                                @enderror
                            </div>
                        </div>

                        <button type="submit" class="btn btn-primary mt-3">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('page-level-scripts')
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script type="text/javascript" src="https://unpkg.com/trix@2.0.8/dist/trix.umd.min.js"></script>
@endsection

resources/views/admin-panel/posts/index.blade.php
@extends('admin-panel.layouts.admin')

@section('admin-panel-content')
    <div class="container px-4 mt-4">
        <div class="row">
            <div class="col-md-12">
                <div class="card mb-4">
                    <div class="card-header">
                        <div class="d-flex justify-content-between">
                            <div>
                                <svg class="svg-inline--fa fa-table me-1" aria-hidden="true" focusable="false" data-prefix="fas"
                                    data-icon="table" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"
                                    data-fa-i2svg="">
                                    <path fill="currentColor"
                                        d="M64 256V160H224v96H64zm0 64H224v96H64V320zm224 96V320H448v96H288zM448 256H288V160H448v96zM64 32C28.7 32 0 60.7 0 96V416c0 35.3 28.7 64 64 64H448c35.3 0 64-28.7 64-64V96c0-35.3-28.7-64-64-64H64z">
                                    </path>
                                </svg><!-- <i class="fas fa-table me-1"></i> Font Awesome fontawesome.com -->
                                <h1 class="mt-4 d-inline">Posts</h1>
                            </div>
                            <a href="{{ route('posts.create') }}" class="btn btn-outline-primary">Add Post</a>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="datatable-wrapper datatable-loading no-footer sortable searchable fixed-columns">
                            {{-- <div class="datatable-top">
                                <div class="datatable-dropdown">
                                    <label>
                                        <select class="datatable-selector">
                                            <option value="5">5</option>
                                            <option value="10" selected="">10</option>
                                            <option value="15">15</option>
                                            <option value="20">20</option>
                                            <option value="25">25</option>
                                        </select> entries per page
                                    </label>
                                </div>
                                <div class="datatable-search">
                                    <input class="datatable-input" placeholder="Search..." type="search"
                                        title="Search within table" aria-controls="datatablesSimple">
                                </div>
                            </div> --}}
                            <div class="datatable-container">
                                <table id="datatablesSimple" class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Image</th>
                                            <th>Title</th>
                                            <th>Excerpt</th>
                                            <th>Body</th>
                                            <th>Status</th>
                                            <th>Category</th>
                                            <th>Author Name</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($posts as $post)
                                        <tr>
                                            <td>{{ $post->id }}</td>
                                            <td>
                                                <img src="{{ asset($post->image) }}" alt="{{ $post->title }}" style="max-width: 100px">
                                            </td>
                                            <td>{{ Str::limit($post->title, 10) }}</td>
                                            <td>{{ Str::limit($post->excerpt, 10) }}</td>
                                            <td>{{ Str::limit($post->body, 10) }}</td>
                                            <td>{!! $post->status !!}</td>
                                            <td>{{ $post->category->name }}</td>
                                            <td>{{ $post->author->name }}</td>
                                            <td>
                                                <a href="{{ route('posts.edit', $post) }}" class="btn btn-warning">
                                                    <i class="fa-solid fa-pencil"></i>
                                                </a>
                                                <button data-delete-route="{{ route('posts.destroy', $post) }}" class="btn btn-danger delete-post">
                                                    <i class="fa-solid fa-trash"></i>
                                                </button>
                                                @if (! $post->is_published)
                                                    <button data-publish-route="{{ route('posts.publish', $post) }}" class="btn btn-info publish-post">
                                                        <i class="fa-solid fa-upload"></i>
                                                    </button>
                                                @endif
                                            </td>
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                            <div class="datatable-bottom">
                                {{ $posts->links() }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="deleteModal" tabindex="-1">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                      <p>Are you sure you want to delete this post?</p>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                      <form action="" class="d-inline-block" id="deleteForm" method="POST">
                        @csrf
                        @method('delete')
                        <button type="submit" class="btn btn-primary">Save changes</button>
                      </form>

                    </div>
                  </div>
                </div>
            </div>
            <div class="modal fade" id="publishModal" tabindex="-1">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="publishModalLabel">Publish Post?</h5>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                      <p>Are you sure you want to publish this post right now?</p>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                      <form action="" class="d-inline-block" id="publishForm" method="POST">
                        @csrf
                        @method('put')
                        <button type="submit" class="btn btn-primary">Save changes</button>
                      </form>

                    </div>
                  </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('page-level-scripts')
    <script src="{{ asset('admin/js/page-level/posts/index.js') }}"></script>
@endsection